name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Fix the const issue
      run: |
        mv const-fix.patch ./libraries/amazon/amazon-kinesis-video-streams-media-interface
        cd ./libraries/amazon/amazon-kinesis-video-streams-media-interface
        git apply const-fix.patch

    - name: Edit the constants
      run: |
        sed -i '' 's/us-east-1/us-west-2/g' ./samples/kvsapp/sample_config.h
        sed -i '' 's/kvs_example_camera_stream/demo-stream/g' ./samples/kvsapp/sample_config.h


    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(sysctl -n hw.cpu)

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

    - name: Run the sample
      working-directory: ./build
      run: |
        ./bin/kvsappcli

